version: '3.4'

services:
  veritas_backend:
    image: ${DOCKER_REGISTRY-}veritasbackend
    build:
      context: .
      dockerfile: veritas_backend/Dockerfile

    volumes:
        - ./veritas_backend:/app
    depends_on:
        - veritas_db
    tty: true
    stdin_open: true

  veritas_db:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    volumes:
        - ./db-data:/var/opt/mssql/data
    ports:
        - "1434:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password123
